data:
  raw_path: "data/raw/Dataset.csv"
  processed_dir: "data/processed"
  train_file: "train.csv"
  val_file: "val.csv"
  test_file: "test.csv"
  
columns:
  id_col: "Patient_ID"
  time_col: "ICULOS"
  label_col: "SepsisLabel"
  static_cols: ["Age", "Gender", "HospAdmTime", "Unit1", "Unit2"]
  vital_cols: ["HR", "O2Sat", "Temp", "SBP", "MAP", "DBP", "Resp", "EtCO2"]
  lab_cols: ["BaseExcess", "HCO3", "FiO2", "pH", "PaCO2", "SaO2", "AST", "BUN",
             "Alkalinephos", "Calcium", "Chloride", "Creatinine", "Bilirubin_direct",
             "Glucose", "Lactate", "Magnesium", "Phosphate", "Potassium",
             "Bilirubin_total", "TroponinI", "Hct", "Hgb", "PTT", "WBC",
             "Fibrinogen", "Platelets"]

model:
  type: "xgboost"
  random_state: 42
  n_estimators: 500
  max_depth: 6
  learning_rate: 0.05

paths:
  model_dir: "models"
  model_name: "sepsis_xgb.pkl"